name: Manage Docker

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action to perform: [start, stop]'
        required: true
        type: string
        default: 'start'

jobs:
  docker-compose-job:
    runs-on: ubuntu-latest

    steps:
      - name: Execute action on the server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          port: 55555
          script: |
            cd apps/sandbox/sveltekit
            if [ "${{ github.event.inputs.action }}" = "start" ]; then
              echo "Starting the Docker Compose stack..."
              docker-compose up -d
            elif [ "${{ github.event.inputs.action }}" = "stop" ]; then
              echo "Stopping the Docker Compose stack..."
              docker-compose down
            else
              echo "Invalid action: '${{ github.event.inputs.action }}'. Use 'start' or 'stop'."
              exit 1
            fi
