name: Start/Stop Manual Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action to perform: [start, stop]'
        required: true
        type: string
        default: 'start'

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Validate selection and execute action
        run: |
          case "${{ github.event.inputs.action }}" in
            start)
              echo "Executing START action..."
              ;;
            stop)
              echo "Executing STOP action..."
              ;;
            *)
              echo "Invalid action specified: '${{ github.event.inputs.action }}'. Please choose 'start' or 'stop'."
              exit 1
              ;;
          esac
